server:
  port: 8081

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: postgres
    password: Asdfg0-/
    driverClassName: org.postgresql.Driver
    platform: postgres